Running docker build in quiet mode; streaming docker stack config to new comose file and using that as stack compose file

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -35,15 +35,15 @@ jobs:
 
           echo "Moving ${SERVE_PATH} to ${OLD_SERVE_PATH} and replacing with dist..."
           if [ -d $SERVE_PATH ]; then
-            if mv $SERVE_PATH $OLD_SERVE_PATH && mv dist $SERVE_PATH; then
+            if mv ${SERVE_PATH}/ $OLD_SERVE_PATH && mv dist/ $SERVE_PATH; then
               echo "Folders moved successfully!"
             else
               echo "Folder move failed. Restoring ${SERVE_PATH}..."
-              mv $OLD_SERVE_PATH $SERVE_PATH || echo "Restore failed! Please check manually."
+              mv ${OLD_SERVE_PATH}/ $SERVE_PATH || echo "Restore failed! Please check manually."
               exit 1
             fi
           else
-          echo "Created frontend folder at $SERVE_PATH"
+            echo "Created frontend folder at $SERVE_PATH"
             mkdir -p $SERVE_PATH
-            mv dist $SERVE_PATH
+            mv dist/ $SERVE_PATH
           fi        
